## 键值对冒号后面，必须空一格
home: 
 province: 陕西省-dev 
 city: 宝鸡市
 desc: 我家住在${home.province}的${home.city}

## jdbc 配置
spring.datasource.url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

## Mybatis 配置
mybatis.typeAliasesPackage: com.lls.springboot.bean
mybatis.mapperLocations: classpath:mapper/*.xml

## token过期时间
validate:
  hours: 1

#rabbitMQ 
spring.application.name: rabbitmq
spring.rabbitmq.host: localhost
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest

#email
spring.mail.host: smtp.qq.com
spring.mail.username: 1942625600@qq.com
spring.mail.password: wpllsliulongjie8
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.starttls.required: true